### PR TITLE
Implemented multiple driver backends

### PR DESCRIPTION
**Pull request by JustDevZero**
This little changes allow the bot to use any engine supported by sqlachemy.

### CODE REVIEW

**Comment by sharkbound** [comment]
thanks, i am working on improving the command server atm, then i will deal with this

**Comment by tisboyo** [comment]
Looks like a very simple change, though will be breaking for those not expecting it. Unsure of the number of people currently using mysql though.

**Comment by sharkbound** [comment]
@tisboyo its probably better to get breaking changes done earlier better than later though, but if i just add the driver config option it should keep backwards compatibility since it will get auto-added to the config

**Comment by JustDevZero** [comment]
@sharkbound yup, sooner or later you'll get breaking changes.

But... @tisboyo with this changes, as I add the driver option with a default mysql if won't break changes for anyone.

If you where already using mysql+mysqlconnector the file will just fill the missing default connector: mysql+mysqlconnector

If you where using sqlite, as it's gots 'enabled' on false, and defaults on f'sqlite:///{DB_FILENAME}'

Of couse, if you have messed with the session.py and added a custom driver manually, of course, then it breaks stuff, but I doupt that's your case or anyone's.

I tested and yeah, it works. And now I've got a working bot with postgres :D

**Comment by JustDevZero** [comment]
Yup, as I said, i really doupts that's anyone case. If you need to modify stuff, you fork stuff, not hot patch. :D

**Comment by tisboyo** [comment]
> But... @tisboyo with this changes, as I add the driver option with a default mysql if won't break changes for anyone.

I didn't see in the code where it defaults to mysql, which is why I mentioned it. I'm ready for the change though personally, but also looking out for the project as a whole. Overall I think this is the right move though.

**Comment by sharkbound** [comment]
about the timing for doing these changes @JustDevZero i am working on the command server rewrite first, which should not take too long as its a complex one, then i will include these changes in that same update, and since its a more major change, i will be releasing it as version 2.0.0 when its done

**Comment by sharkbound** [comment]
merged manually, gave credit in a commit message for the changes 863eb6585b3df865f7a62254f529398957e6e848

**Pull request closed without merging**
