### PR TITLE
Adding Raid alert support

### PR DESCRIPTION
**Pull request by netmasa**
I have not fully tested this and it's been awhile since I've used python (I'll probably have my bot running next stream so we'll see there if the Raid feature works, haha). 

I'm open to changes, but really wanted to see Raid support added.

Also added the two other gift sub notices, to the list of things that trigger the subscriptions. They probably could be further supported though.

Apologies for the number of commits, it's quicker to just edit it on the web :P

Thanks for this project, way faster than having to write my own!

### CODE REVIEW

**Comment by sharkbound** [comment]
merged it into a new branch called, raid_support, il do some testing too

**Comment by sharkbound** [comment]
https://github.com/sharkbound/PythonTwitchBotFramework/tree/raid_support

**Comment by sharkbound** [comment]
Thanks for taking the time to help out

**Comment by sharkbound** [comment]
from my testing it works fine
the changes have been pushed to master and added to the pypi version
initial version that added the raid changes is `PythonTwitchBotFramework 1.5.13 `

**Comment by netmasa** [comment]
Awesome!

**Pull request merged**
